on:
  push:

name: Check for regressions in static analysis kernel

jobs:
  check_regressions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - { org: "google", name: "guava", expectedErrorsOsvScanner: 6, expectedErrorsTrivy: 29 }
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout test repositories
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo.org }}/${{ matrix.repo.name }}
          path: ${{ matrix.repo.org }}/${{ matrix.repo.name }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install unzip curl
      - name: Install osv-scanner
        run: |
          curl -L -o "/tmp/osv-scanner.zip" "https://github.com/DataDog/osv-scanner/releases/download/v0.9.0/osv-scanner_linux_amd64.zip" >/dev/null 2>&1 || exit 1
          (cd /tmp && unzip osv-scanner.zip)
          sudo mv /tmp/osv-scanner /usr/bin/osv-scanner
          sudo chmod 755 /usr/bin/osv-scanner
      - name: Install trivy
        run: |
          curl -L -o /tmp/trivy.deb "https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb"
          sudo dpkg -i /tmp/trivy.deb
      - name: Run on repo
        run: ./misc/compare-sboms.sh ${{ matrix.repo.org }}/${{ matrix.repo.name }} ${{ matrix.repo.expectedErrorsOsvScanner }} ${{ matrix.repo.expectedErrorsTrivy }}
