on: push

name: Comparison with other SBOM tools
jobs:
  test-maven:
    runs-on: ubuntu-latest
    name: Run testsuite for Maven
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Stable + Rustfmt + Clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: run integration tests
      run: ./misc/test.sh